import { MigrationInterface, QueryRunner } from "typeorm";

export class BackendMigration1742501892879 implements MigrationInterface {
    name = 'BackendMigration1742501892879'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."social_media_type_enum" AS ENUM('Facebook', 'Twitter', 'Instagram', 'LinkedIn', 'YouTube', 'WhatsApp', 'Telegram', 'Pinterest', 'Snapchat', 'TikTok')`);
        await queryRunner.query(`CREATE TYPE "public"."social_media_status_enum" AS ENUM('Active', 'Inactive', 'Blocked', 'Deleted')`);
        await queryRunner.query(`CREATE TABLE "social_media" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "public"."social_media_type_enum" NOT NULL, "link" character varying(100) NOT NULL, "status" "public"."social_media_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_54ac0fd97432069e7c9ab567f8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54ac0fd97432069e7c9ab567f8" ON "social_media" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."transaction_status_enum" AS ENUM('success', 'pending', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "transaction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "externalId" character varying(255) NOT NULL, "AdjudicadosId" character varying(255), "status" "public"."transaction_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid NOT NULL, CONSTRAINT "UQ_a1b19b56f68e9142139aa9219bd" UNIQUE ("externalId"), CONSTRAINT "PK_89eadb93a89810556e1cbcd6ab9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_gender_enum" AS ENUM('Male', 'Female', 'Other', 'PreferNotToSay')`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_enum" AS ENUM('Admin', 'User', 'Guest', 'Doctor')`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('Active', 'Inactive', 'Blocked', 'Deleted')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(50), "phone_number" character varying(15), "first_name" character varying(30) NOT NULL, "last_name" character varying(30) NOT NULL, "birth_date" TIMESTAMP, "password" character varying(60) NOT NULL, "identification_document" character varying, "gender" "public"."user_gender_enum" NOT NULL, "profile_picture" character varying, "profile_picture_key" character varying, "role" "public"."user_role_enum" NOT NULL, "status" "public"."user_status_enum" NOT NULL, "last_access" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_01eea41349b6c9275aec646eee0" UNIQUE ("phone_number"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cace4a159ff9f2512dd4237376" ON "user" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."surgery_type_enum" AS ENUM('Rhinoplasty', 'Facelift', 'Blepharoplasty', 'Otoplasty', 'BuccalFatRemoval', 'BreastAugmentation', 'BreastLift', 'BreastReduction', 'Liposuction', 'TummyTuck', 'LiposuctionWithTummyTuck', 'LiposuctionWithButtockAugmentation', 'SkinLesionTreatment', 'ButtockAugmentation')`);
        await queryRunner.query(`CREATE TYPE "public"."surgery_category_enum" AS ENUM('FacialSurgeries', 'BreastSurgeries', 'BodySurgeries', 'ReconstructiveSurgeries', 'GeneralSurgeries')`);
        await queryRunner.query(`CREATE TYPE "public"."surgery_subcategory_enum" AS ENUM('EyelidSurgery', 'Facelift', 'BreastAugmentation', 'BreastReduction', 'BreastLift', 'Liposuction', 'TummyTuck', 'ButtockLift')`);
        await queryRunner.query(`CREATE TYPE "public"."surgery_status_enum" AS ENUM('Active', 'Inactive', 'Blocked', 'Deleted')`);
        await queryRunner.query(`CREATE TABLE "surgery" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "rating" integer NOT NULL DEFAULT '0', "amount" double precision NOT NULL, "type" "public"."surgery_type_enum" NOT NULL, "category" "public"."surgery_category_enum" NOT NULL, "subcategory" "public"."surgery_subcategory_enum" DEFAULT 'BreastAugmentation', "status" "public"."surgery_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "fileBannerId" uuid, CONSTRAINT "REL_0857e1e9c522b1a0072b206082" UNIQUE ("fileBannerId"), CONSTRAINT "PK_2e963fc0e35d07a36e15f331754" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2e963fc0e35d07a36e15f33175" ON "surgery" ("id") `);
        await queryRunner.query(`CREATE TABLE "surgery_doctor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "doctorId" uuid, "surgeryId" uuid, CONSTRAINT "PK_f488d917066bcbf1c35cedc543e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."doctor_status_enum" AS ENUM('Active', 'Inactive', 'Blocked', 'Deleted')`);
        await queryRunner.query(`CREATE TABLE "doctor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "profession" character varying, "description" text, "country" text, "provincia" text, "status" "public"."doctor_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" uuid, "curriculumId" uuid, CONSTRAINT "REL_e573a17ab8b6eea2b7fe9905fa" UNIQUE ("userId"), CONSTRAINT "REL_d6b283b8d8084618fe18145cb2" UNIQUE ("curriculumId"), CONSTRAINT "PK_ee6bf6c8de78803212c548fcb94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ee6bf6c8de78803212c548fcb9" ON "doctor" ("id") `);
        await queryRunner.query(`CREATE TABLE "locality" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "iso_code" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_c0445d9b8706ac2d31be91c9b6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c0445d9b8706ac2d31be91c9b6" ON "locality" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."adjudicated_status_enum" AS ENUM('Active', 'Inactive', 'Blocked', 'Deleted')`);
        await queryRunner.query(`CREATE TYPE "public"."adjudicated_adjudicated_status_enum" AS ENUM('Active', 'Verified', 'Validating', 'Rejected', 'Blocked')`);
        await queryRunner.query(`CREATE TABLE "adjudicated" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quota_price" integer, "total_price" integer, "quotas_number" integer, "quotas_paid" integer, "date_surgery" TIMESTAMP, "start_date_payment" TIMESTAMP, "end_date_payment" TIMESTAMP, "comments" character varying, "status" "public"."adjudicated_status_enum" NOT NULL, "adjudicated_status" "public"."adjudicated_adjudicated_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "userId" uuid, "doctorId" uuid, "localityId" uuid, "surgeryId" uuid, CONSTRAINT "PK_9c0df47752f4c935b7d399604ec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c0df47752f4c935b7d399604e" ON "adjudicated" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_method_status_enum" AS ENUM('Active', 'Inactive', 'Blocked', 'Deleted')`);
        await queryRunner.query(`CREATE TABLE "payment_method" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "icon_image" character varying NOT NULL, "icon_image_key" character varying NOT NULL, "type" character varying NOT NULL, "status" "public"."payment_method_status_enum" NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_7744c2b2dd932c9cf42f2b9bc3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7744c2b2dd932c9cf42f2b9bc3" ON "payment_method" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_status_enum" AS ENUM('Pending', 'Paid', 'Proximity', 'Rejected', 'Canceled')`);
        await queryRunner.query(`CREATE TABLE "payment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."payment_status_enum" NOT NULL, "total" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fcaec7df5adf9cac408c686b2a" ON "payment" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."file_db_file_type_enum" AS ENUM('CURRICULUM_VITAE', 'DOCTOR_PHOTOS', 'DOCTOR_VIDEOS', 'SURGERY_PHOTOS', 'SURGERY_VIDEOS', 'PAYMENT_RECEIPT')`);
        await queryRunner.query(`CREATE TABLE "file_db" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_name" character varying NOT NULL, "file_type" "public"."file_db_file_type_enum" NOT NULL, "file_link" character varying NOT NULL, "file_key" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid, "surgery_id" uuid, CONSTRAINT "PK_eaed10c15393913d3ac1e9c3e6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eaed10c15393913d3ac1e9c3e6" ON "file_db" ("id") `);
        await queryRunner.query(`CREATE TABLE "doctor_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "registration_number" character varying NOT NULL, "specialty" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_ac615d3ecf8ec5631b25d3a7742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac615d3ecf8ec5631b25d3a774" ON "doctor_applications" ("id") `);
        await queryRunner.query(`CREATE TABLE "ad" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" character varying NOT NULL, "link" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_0193d5ef09746e88e9ea92c634d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0193d5ef09746e88e9ea92c634" ON "ad" ("id") `);
        await queryRunner.query(`CREATE TYPE "public"."evidence_type_enum" AS ENUM('youtube', 'media')`);
        await queryRunner.query(`CREATE TABLE "evidence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image" character varying NOT NULL, "link" character varying NOT NULL, "type" "public"."evidence_type_enum" NOT NULL DEFAULT 'media', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "doctorId" uuid, CONSTRAINT "PK_b864cb5d49854f89917fc0b44b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b864cb5d49854f89917fc0b44b" ON "evidence" ("id") `);
        await queryRunner.query(`CREATE TABLE "code_reference" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying NOT NULL, "name" character varying NOT NULL, "count" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a67e9b81412e2fc66c26e1408c5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a67e9b81412e2fc66c26e1408c" ON "code_reference" ("id") `);
        await queryRunner.query(`CREATE TABLE "user_social_media_social_media" ("userId" uuid NOT NULL, "socialMediaId" uuid NOT NULL, CONSTRAINT "PK_035185952b78f284890abe568eb" PRIMARY KEY ("userId", "socialMediaId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a1fb8f9055ce2c6067fe3f6f31" ON "user_social_media_social_media" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2fc0585482b86e679d72f199a9" ON "user_social_media_social_media" ("socialMediaId") `);
        await queryRunner.query(`ALTER TABLE "transaction" ADD CONSTRAINT "FK_605baeb040ff0fae995404cea37" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery" ADD CONSTRAINT "FK_0857e1e9c522b1a0072b206082d" FOREIGN KEY ("fileBannerId") REFERENCES "file_db"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_doctor" ADD CONSTRAINT "FK_fdef2e28817ebffabf4d39787d8" FOREIGN KEY ("doctorId") REFERENCES "doctor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surgery_doctor" ADD CONSTRAINT "FK_e21f79cbd6670d4ad6a4d9f61c0" FOREIGN KEY ("surgeryId") REFERENCES "surgery"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor" ADD CONSTRAINT "FK_e573a17ab8b6eea2b7fe9905fa8" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "doctor" ADD CONSTRAINT "FK_d6b283b8d8084618fe18145cb27" FOREIGN KEY ("curriculumId") REFERENCES "file_db"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjudicated" ADD CONSTRAINT "FK_9c62d02b7c32a65e796a0176bfb" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjudicated" ADD CONSTRAINT "FK_8a89c5cb755bba556668cf190c5" FOREIGN KEY ("doctorId") REFERENCES "doctor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjudicated" ADD CONSTRAINT "FK_6d17f818b9e8a997bcd2c3e8bfa" FOREIGN KEY ("localityId") REFERENCES "locality"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjudicated" ADD CONSTRAINT "FK_2cd049072249e6a892371957e7d" FOREIGN KEY ("surgeryId") REFERENCES "surgery"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_db" ADD CONSTRAINT "FK_7477b517162697db16c59d5942b" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_db" ADD CONSTRAINT "FK_ed105bccc6b83baebdbdb3371a0" FOREIGN KEY ("surgery_id") REFERENCES "surgery"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "evidence" ADD CONSTRAINT "FK_9a0f4db3858ac017933e5b7482b" FOREIGN KEY ("doctorId") REFERENCES "doctor"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_social_media_social_media" ADD CONSTRAINT "FK_a1fb8f9055ce2c6067fe3f6f31e" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_social_media_social_media" ADD CONSTRAINT "FK_2fc0585482b86e679d72f199a90" FOREIGN KEY ("socialMediaId") REFERENCES "social_media"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_social_media_social_media" DROP CONSTRAINT "FK_2fc0585482b86e679d72f199a90"`);
        await queryRunner.query(`ALTER TABLE "user_social_media_social_media" DROP CONSTRAINT "FK_a1fb8f9055ce2c6067fe3f6f31e"`);
        await queryRunner.query(`ALTER TABLE "evidence" DROP CONSTRAINT "FK_9a0f4db3858ac017933e5b7482b"`);
        await queryRunner.query(`ALTER TABLE "file_db" DROP CONSTRAINT "FK_ed105bccc6b83baebdbdb3371a0"`);
        await queryRunner.query(`ALTER TABLE "file_db" DROP CONSTRAINT "FK_7477b517162697db16c59d5942b"`);
        await queryRunner.query(`ALTER TABLE "adjudicated" DROP CONSTRAINT "FK_2cd049072249e6a892371957e7d"`);
        await queryRunner.query(`ALTER TABLE "adjudicated" DROP CONSTRAINT "FK_6d17f818b9e8a997bcd2c3e8bfa"`);
        await queryRunner.query(`ALTER TABLE "adjudicated" DROP CONSTRAINT "FK_8a89c5cb755bba556668cf190c5"`);
        await queryRunner.query(`ALTER TABLE "adjudicated" DROP CONSTRAINT "FK_9c62d02b7c32a65e796a0176bfb"`);
        await queryRunner.query(`ALTER TABLE "doctor" DROP CONSTRAINT "FK_d6b283b8d8084618fe18145cb27"`);
        await queryRunner.query(`ALTER TABLE "doctor" DROP CONSTRAINT "FK_e573a17ab8b6eea2b7fe9905fa8"`);
        await queryRunner.query(`ALTER TABLE "surgery_doctor" DROP CONSTRAINT "FK_e21f79cbd6670d4ad6a4d9f61c0"`);
        await queryRunner.query(`ALTER TABLE "surgery_doctor" DROP CONSTRAINT "FK_fdef2e28817ebffabf4d39787d8"`);
        await queryRunner.query(`ALTER TABLE "surgery" DROP CONSTRAINT "FK_0857e1e9c522b1a0072b206082d"`);
        await queryRunner.query(`ALTER TABLE "transaction" DROP CONSTRAINT "FK_605baeb040ff0fae995404cea37"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fc0585482b86e679d72f199a9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1fb8f9055ce2c6067fe3f6f31"`);
        await queryRunner.query(`DROP TABLE "user_social_media_social_media"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a67e9b81412e2fc66c26e1408c"`);
        await queryRunner.query(`DROP TABLE "code_reference"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b864cb5d49854f89917fc0b44b"`);
        await queryRunner.query(`DROP TABLE "evidence"`);
        await queryRunner.query(`DROP TYPE "public"."evidence_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0193d5ef09746e88e9ea92c634"`);
        await queryRunner.query(`DROP TABLE "ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac615d3ecf8ec5631b25d3a774"`);
        await queryRunner.query(`DROP TABLE "doctor_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaed10c15393913d3ac1e9c3e6"`);
        await queryRunner.query(`DROP TABLE "file_db"`);
        await queryRunner.query(`DROP TYPE "public"."file_db_file_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fcaec7df5adf9cac408c686b2a"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP TYPE "public"."payment_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7744c2b2dd932c9cf42f2b9bc3"`);
        await queryRunner.query(`DROP TABLE "payment_method"`);
        await queryRunner.query(`DROP TYPE "public"."payment_method_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c0df47752f4c935b7d399604e"`);
        await queryRunner.query(`DROP TABLE "adjudicated"`);
        await queryRunner.query(`DROP TYPE "public"."adjudicated_adjudicated_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."adjudicated_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0445d9b8706ac2d31be91c9b6"`);
        await queryRunner.query(`DROP TABLE "locality"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee6bf6c8de78803212c548fcb9"`);
        await queryRunner.query(`DROP TABLE "doctor"`);
        await queryRunner.query(`DROP TYPE "public"."doctor_status_enum"`);
        await queryRunner.query(`DROP TABLE "surgery_doctor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2e963fc0e35d07a36e15f33175"`);
        await queryRunner.query(`DROP TABLE "surgery"`);
        await queryRunner.query(`DROP TYPE "public"."surgery_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."surgery_subcategory_enum"`);
        await queryRunner.query(`DROP TYPE "public"."surgery_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."surgery_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cace4a159ff9f2512dd4237376"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_gender_enum"`);
        await queryRunner.query(`DROP TABLE "transaction"`);
        await queryRunner.query(`DROP TYPE "public"."transaction_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54ac0fd97432069e7c9ab567f8"`);
        await queryRunner.query(`DROP TABLE "social_media"`);
        await queryRunner.query(`DROP TYPE "public"."social_media_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."social_media_type_enum"`);
    }

}
